series: Basic C++
title: Number Guessing Game
author:
  name: David I. Schwartz, Ph.D.
  email: 
  github: https://github.com/IGME-RIT
description: A small console game using concepts from previous demos.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: C++ Console IO