series: C++ IO
title: Number Guessing Game
author:
  name: David I. Schwartz, Ph.D.
  email: 
  github: https://github.com/IGME-RIT
description: Using concepts from the basic io demo, build a small console game.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: C++ IO
    title: Basic Console IO